import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Contact Page",
    description: "Generated by create next app",
    keywords: "nextjs, reactjs, typescript, javascript",
};

export default function ContactPage() {
    return (
        <>
            <span>Contact Page</span>   
        </>
    )
}
