import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Second Page",
    description: "Generated by create next app",
    keywords: "nextjs, reactjs, typescript, javascript",
};

export default function AboutPage() {
    return (
        <>
            <span>About Page</span>   
        </>
    )
}
